# docker-compose.yml
version: '3.7'
services:
  nestjs-skeleton-back:
    build:
      context: ..
      args:
        - PORT=${PORT}
      dockerfile: ./docker/Dockerfile
      target: dev
    image: ${IMAGE_NAME}:dev
    container_name: ${IMAGE_NAME}
    hostname: localhost
    restart: always
    depends_on:
      - nestjs-skeleton-back-db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_NAME}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
    ports:
      - '3000:3000'

  nestjs-skeleton-back-db:
    image: postgres:16
    container_name: nestjs-skeleton-back-db
    hostname: nestjs-skeleton-back-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - ${POSTGRES_PORT}:5432
