name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: ✅ Validate project
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout project
        uses: actions/checkout@v4

      - name: 🧙‍♂️ Setup environment
        uses: ./.github/actions/setup-environment

      - name: 🖍️ Check types
        run: npm run check:types

      - name: 💅 Check format
        run: npm run check:format

      - name: 📑 Check lint
        run: npm run check:lint

      - name: 🔤 Check spelling
        run: npm run check:spelling

  test:
    name: 🧑‍🔬 Test project
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: ⬇️ Checkout project
        uses: actions/checkout@v4

      - name: 🧙‍♂️ Setup environment
        uses: ./.github/actions/setup-environment

      - name: 🧪 Run tests
        run: npm run test:cov | true

  # build:
  #   name: 🧰 Push image to DockerHub
  #   runs-on: ubuntu-latest
  #   needs: test

  #   steps:
  #     - name: ⬇️ Checkout project
  #       uses: actions/checkout@v4

  # - name: 🔑 Log in to Docker Hub
  #   uses: docker/login-action@v3
  #   with:
  #     username: ${{ secrets.DOCKER_USERNAME }}
  #     password: ${{ secrets.DOCKER_PASSWORD }}

  # - name: 🐳 Extract metadata for Docker
  #   id: meta
  #   uses: docker/metadata-action@v4
  #   with:
  #     images: ${{ secrets.DOCKER_USERNAME }}/repository-name

  # - name: 🐳 Build and Push Docker image
  #   uses: docker/build-push-action@v5
  #   with:
  #     context: .
  #     file: docker/Dockerfile
  #     push: true
  #     tags: |
  #       ${{ secrets.DOCKER_USERNAME }}/repository-name:develop-${{ github.sha }}
  #       ${{ secrets.DOCKER_USERNAME }}/repository-name:develop
  #     labels: ${{ steps.meta.outputs.labels }}

  # deploy:
  #   name: 🚀 Deploy
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: ⬇️ Checkout project
  #       uses: actions/checkout@v4
